# Generated by Django 4.0.4 on 2022-07-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=30)),
                ('user_type', models.CharField(max_length=20)),
                ('user_suscriber', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('estado_venta', models.CharField(max_length=20)),
                ('monto_venta', models.IntegerField()),
                ('direccion_venta', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=20)),
                ('stock_producto', models.IntegerField()),
                ('categoria_producto', models.CharField(max_length=30)),
                ('descripcion_producto', models.CharField(max_length=100)),
                ('img_producto', models.ImageField(upload_to='')),
                ('precio_producto', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
